plugins {
    id 'java'
    id 'io.qameta.allure' version '2.12.0'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

repositories {
    mavenCentral()
}

ext {
    junitVersion      = '5.12.0'
    seleniumVersion   = '4.29.0'
    restAssuredVersion = '5.5.1'
    allureVersion     = '2.29.1'
}

dependencies {
    // JUnit 5
    testImplementation "org.junit.jupiter:junit-jupiter:${junitVersion}"
    testImplementation "org.junit.jupiter:junit-jupiter-api:${junitVersion}"
    testImplementation "org.junit.jupiter:junit-jupiter-params:${junitVersion}"
    testRuntimeOnly    "org.junit.jupiter:junit-jupiter-engine:${junitVersion}"
    testRuntimeOnly    "org.junit.platform:junit-platform-launcher:1.12.0"

    // Selenium
    implementation "org.seleniumhq.selenium:selenium-java:${seleniumVersion}"

    // AssertJ
    testImplementation 'org.assertj:assertj-core:3.27.3'

    // REST Assured
    testImplementation "io.rest-assured:rest-assured:${restAssuredVersion}"
    testImplementation "io.rest-assured:json-path:${restAssuredVersion}"
    testImplementation "io.rest-assured:rest-assured-common:${restAssuredVersion}"

    // Allure
    testImplementation "io.qameta.allure:allure-junit5:${allureVersion}"
    testImplementation "io.qameta.allure:allure-rest-assured:${allureVersion}"

    // WebDriverManager
    implementation 'io.github.bonigarcia:webdrivermanager:5.9.3'

    // Logging
    implementation 'org.slf4j:slf4j-api:2.1.0-alpha1'
    implementation 'ch.qos.logback:logback-classic:1.5.17'
}

allure {
    version = "${allureVersion}"
    useJUnit5 {
        version = "${allureVersion}"
    }
}

test {
    useJUnitPlatform {
        includeTags 'lesson_18'
    }
    systemProperty 'allure.results.directory', 'build/allure-results'
    testLogging {
        events "passed", "skipped", "failed"
    }
}